# Generated by Django 4.1.7 on 2023-04-06 18:42

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SumUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='생성일')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='수정일')),
                ('j_name', models.CharField(blank=True, help_text='적요명', max_length=35, null=True)),
                ('transaction', models.CharField(choices=[('INCOME', '수입'), ('SPENDING', '지출')], max_length=300)),
                ('trade_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
