# Generated by Django 4.1.7 on 2023-04-07 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='생성일')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='수정일')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='금액(KRW)')),
                ('description', models.CharField(help_text='설명', max_length=100, null=True)),
                ('managed', models.BooleanField(default=True, help_text='관리여부')),
                ('email', models.ForeignKey(help_text='이메일', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trade_type', models.ForeignKey(blank=True, choices=[('식비', '식비'), ('생활', '생활'), ('교통', '교통'), ('쇼핑/뷰티', '쇼핑/뷰티'), ('의료/건강', '의료/건강'), ('문화/여가', '문화/여가'), ('미분류', '미분류')], help_text='Trade type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
