# Generated by Django 4.1.7 on 2023-04-06 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDetail',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='생성일')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='수정일')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.ForeignKey(help_text='이메일', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='생성일')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='수정일')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('base', models.IntegerField(help_text='총 입금액(KRW)')),
                ('transaction', models.CharField(choices=[('INCOME', '수입'), ('SPENDING', '지출')], max_length=10)),
                ('email', models.ForeignKey(help_text='이메일', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
