# Generated by Django 4.1.7 on 2023-04-06 08:45

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_asset_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, help_text='생성일')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='수정일')),
                ('j_name', models.CharField(blank=True, help_text='적요명', max_length=35, null=True)),
                ('trade_type', models.CharField(blank=True, choices=[("[('INPUT', '원화 입금'), ('OUTPUT', '원화 출금'), ('INPUT_USD', '외화 입금'), ('OUTPUT_USD', '외화 출금'), ('IMPORT', '입고'), ('EXPORT', '출고'), ('DIVIDEND_INPUT', '배당금 입금'), ('DIVIDEND_OUTPUT', '배당금 출금'), ('OVERSEA_TAX', '해외 수수료'), ('OVERSEA_TAX_REFUND', '해외 수수료 반환')]", 'Transaction')], max_length=300, null=True)),
                ('description', models.CharField(blank=True, help_text='설명', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='base',
            field=models.IntegerField(help_text='금액(KRW)'),
        ),
        migrations.DeleteModel(
            name='AssetDetail',
        ),
    ]
