# Generated by Django 4.1.7 on 2023-04-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sumup_alter_asset_base_delete_assetdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SumUp',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='base',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='asset',
            name='managed',
            field=models.BooleanField(default=True, help_text='관리여부'),
        ),
        migrations.AddField(
            model_name='asset',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('INCOME_SALARY', '월급 입금'), ('INCOME_PIN', '용돈 입금'), ('INCOME_CARRY_OVER', '이월 입금'), ('INCOME_WITHDRAWAL', '자산 인출 입금'), ('INCOME_ETC', '자산 인출 입금'), ('SPENDING_FOOD', '식비 출금'), ('SPENDING_TRANSPORTATION', '교통비 출금'), ('SPENDING_CLTURE', '문화생활 출금'), ('SPENDING_BUEATY', '미용 출금'), ('SPENDING_DRESS', '의류 출금'), ('SPENDING_ADU', '교육 출금'), ('SPENDING_MOBILE', '통신비 출금'), ('SPENDING_SAVE', '저축 출금')], max_length=300, null=True),
        ),
    ]
