# Generated by Django 4.1.7 on 2023-03-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_expiringtoken_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ci_hash',
        ),
    ]
